name: load_images
on: [push]
jobs:
  LoadImages:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-2019]
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup flutter
      uses: subosito/flutter-action@master
      with:
        flutter-version: 1.22.x
        channel: 'any'
    - name: pub get
      run: flutter pub get
    - name: flutter test
      run: flutter test
